import CompanyOverviewPage from "@/components/companyOverviewPage";

const exampleCompanyData = {
  id: '123',
  companyLogoUrl: 'https://placehold.co/64x64/007A33/FFFFFF.png?text=G',
  companyName: 'GreenWave Technologies',
  totalJobs: 5,
  overviewContent: {
    about: [
      'GreenWave Technologies is dedicated to providing cutting-edge software solutions that empower businesses to thrive.',
      'Our team specializes in cloud computing, AI-driven analytics, and scalable web platforms. We believe in innovation.',
      'We have collaborated with industry leaders in healthcare, finance, and retail to streamline operations and drive growth.',
      'With offices in Seattle, WA and Austin, TX, GreenWave continues to expand our talented workforce through collaboration and excellence.',
    ],
  },
  jobs: [
    {
      id: '1',
      timePosted: '3 days ago',
      tags: ['onsite - Seattle, WA'],
      companyLogoUrl: 'https://placehold.co/56x56/007A33/FFFFFF.png?text=G',
      jobTitle: 'Backend Engineer',
      companyName:' GreenWave Technologies',
      salaryRange: '110k - 140k USD/year',
      isQuickApply: true,
      isRemote: false,
      location: 'Seattle, WA',
      jobType: 'Full-time',
    },
        {
      id: '15',
      timePosted: '3 days ago',
      tags: ['onsite - Seattle, WA'],
      companyLogoUrl: 'https://placehold.co/56x56/007A33/FFFFFF.png?text=G',
      jobTitle: 'Backend Engineer',
      companyName:' GreenWave Technologies',
      salaryRange: '110k - 140k USD/year',
      isQuickApply: true,
      isRemote: false,
      location: 'Seattle, WA',
      jobType: 'Full-time',
    },
        {
      id: '5',
      timePosted: '3 days ago',
      tags: ['onsite - Seattle, WA'],
      companyLogoUrl: 'https://placehold.co/56x56/007A33/FFFFFF.png?text=G',
      jobTitle: 'Backend Engineer',
      companyName:' GreenWave Technologies',
      salaryRange: '110k - 140k USD/year',
      isQuickApply: true,
      isRemote: false,
      location: 'Seattle, WA',
      jobType: 'Full-time',
    },
        {
      id: '6',
      timePosted: '3 days ago',
      tags: ['onsite - Seattle, WA'],
      companyLogoUrl: 'https://placehold.co/56x56/007A33/FFFFFF.png?text=G',
      jobTitle: 'Backend Engineer',
      companyName:' GreenWave Technologies',
      salaryRange: '110k - 140k USD/year',
      isQuickApply: true,
      isRemote: false,
      location: 'Seattle, WA',
      jobType: 'Full-time',
    },
        {
      id: '7',
      timePosted: '3 days ago',
      tags: ['onsite - Seattle, WA'],
      companyLogoUrl: 'https://placehold.co/56x56/007A33/FFFFFF.png?text=G',
      jobTitle: 'Backend Engineer',
      companyName:' GreenWave Technologies',
      salaryRange: '110k - 140k USD/year',
      isQuickApply: true,
      isRemote: false,
      location: 'Seattle, WA',
      jobType: 'Full-time',
    },
        {
      id: '8',
      timePosted: '3 days ago',
      tags: ['onsite - Seattle, WA'],
      companyLogoUrl: 'https://placehold.co/56x56/007A33/FFFFFF.png?text=G',
      jobTitle: 'Backend Engineer',
      companyName:' GreenWave Technologies',
      salaryRange: '110k - 140k USD/year',
      isQuickApply: true,
      isRemote: false,
      location: 'Seattle, WA',
      jobType: 'Full-time',
    },
        {
      id: '9',
      timePosted: '3 days ago',
      tags: ['onsite - Seattle, WA'],
      companyLogoUrl: 'https://placehold.co/56x56/007A33/FFFFFF.png?text=G',
      jobTitle: 'Backend Engineer',
      companyName:' GreenWave Technologies',
      salaryRange: '110k - 140k USD/year',
      isQuickApply: true,
      isRemote: false,
      location: 'Seattle, WA',
      jobType: 'Full-time',
    },
  ],
  sideBarDetails: {
    companyWebsite: 'https://greenwavetech.com',
  },
};

export default function CompanyPage () {
  return (
    <CompanyOverviewPage {...exampleCompanyData} />
  )
}
